 services:
    db:
        image: holos-image
        deploy:
            replicas: 3
        volumes:
        - "./src:/notebooks"
        - "./cassandra.sh:/start.sh"
        ports:
        - "0.0.0.0:5000-5002:5000"